In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dc = pd.read_csv('raw_dataset/olist_order_reviews_dataset.csv') 
dc.info() 
dc.head()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [3]:
dc.columns.is_unique #Check data duplikat di setiap kolom (output: True)

True

In [4]:
#Check jumlah missing value di setiap kolom  
print('order_id: ', dc['order_id'].isna().sum())
print('review_id: ', dc['review_id'].isna().sum())
print('review_score: ', dc['review_score'].isna().sum())
print('review_comment_title: ', dc['review_comment_title'].isna().sum()) 
print('review_comment_message: ', dc['review_comment_message'].isna().sum()) 
print('review_creation_date: ', dc['review_creation_date'].isna().sum()) 
print('review_answer_timestamp: ', dc['review_answer_timestamp'].isna().sum())

order_id:  0
review_id:  0
review_score:  0
review_comment_title:  87656
review_comment_message:  58247
review_creation_date:  0
review_answer_timestamp:  0

In [5]:
dc['review_comment_title']=dc['review_comment_title'].fillna('No Comment Title') 
dc['review_comment_title'].value_counts(dropna=False)

review_comment_title
No Comment Title             87656
Recomendo                      423
recomendo                      345
Bom                            293
super recomendo                270
                             ...
Nota máxima!                     1
muito bom produto                1
Não foi entregue o pedido        1
OTIMA EMBALAGEM                  1
Foto enganosa                    1
Name: count, Length: 4528, dtype: int64

In [6]:
dc['review_comment_message']=dc['review_comment_message'].fillna('No Comment Message') 
dc['review_comment_message'].value_counts(dropna=False)

review_comment_message
No Comment Message                                                                                                               58247
Muito bom                                                                                                                          230
Bom                                                                                                                                189
muito bom                                                                                                                          122
bom                                                                                                                                107
                                                                                                                                 ...
para este produto recebi de acordo com a compra realizada!                                                                           1
Entregou dentro do prazo. O produto chegou em condições perfeitas. Estou muito satisfeita!                                           1
O produto não foi enviado com NF, não existe venda sem NF, com certeza fico no aguardo do envio da NF podendo ser por e-mail.        1
Excelente mochila, entrega super rápida. Super recomendo essa loja!                                                                  1
meu produto chegou e ja tenho que devolver, pois está com defeito , não segurar carga                                                1
Name: count, Length: 36160, dtype: int64

In [8]:
dc.info()
dc.head()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     99224 non-null  str
 4   review_comment_message   99224 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,No Comment Title,No Comment Message,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,No Comment Title,No Comment Message,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,No Comment Title,No Comment Message,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,No Comment Title,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,No Comment Title,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [9]:
dc['review_creation_date']=pd.to_datetime(dc['review_creation_date'], format='%Y-%m-%d %H:%M:%S')

In [10]:
dc['review_answer_timestamp']=pd.to_datetime(dc['review_answer_timestamp'], format='%Y-%m-%d %H:%M:%S')

In [12]:
dc.info()
dc.tail()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     99224 non-null  str
 4   review_comment_message   99224 non-null  str
 5   review_creation_date     99224 non-null  datetime64[us]
 6   review_answer_timestamp  99224 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(1), str(4)
memory usage: 5.3 MB

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,No Comment Title,No Comment Message,2018-07-07,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,No Comment Title,No Comment Message,2017-12-09,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,No Comment Title,"Excelente mochila, entrega super rápida. Super...",2018-03-22,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,No Comment Title,No Comment Message,2018-07-01,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,No Comment Title,"meu produto chegou e ja tenho que devolver, po...",2017-07-03,2017-07-03 21:01:49

In [13]:
dc.to_csv('clean_dataset/order_review_cleaned.csv', index=False, encoding='utf-8')