In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dc = pd.read_csv('raw_dataset/olist_order_reviews_dataset.csv') 
dc.info() 
dc.head()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [3]:
dc.columns.is_unique #Check data duplikat di setiap kolom (output: True)

True

In [4]:
#Check jumlah missing value di setiap kolom  
print('order_id: ', dc['order_id'].isna().sum())
print('review_id: ', dc['review_id'].isna().sum())
print('review_score: ', dc['review_score'].isna().sum())
print('review_comment_title: ', dc['review_comment_title'].isna().sum()) 
print('review_comment_message: ', dc['review_comment_message'].isna().sum()) 
print('review_creation_date: ', dc['review_creation_date'].isna().sum()) 
print('review_answer_timestamp: ', dc['review_answer_timestamp'].isna().sum())

order_id:  0
review_id:  0
review_score:  0
review_comment_title:  87656
review_comment_message:  58247
review_creation_date:  0
review_answer_timestamp:  0

In [7]:
def comment_title (x):
    if pd.isna(x):
        return 'No Comment Title'

    x = str(x).lower() 
    if 'super' in x and 'recomendo' in x :
        return 'Super recomendo'
    elif 'recomendo' in x:
        return 'Recomendo' 

    return x.title().strip() 
    
dc['review_comment_title'] = dc['review_comment_title'].apply(comment_title) 
dc['review_comment_title'].value_counts(dropna=False)

review_comment_title
No Comment Title             87656
Recomendo                     1396
Super recomendo                682
Ótimo                          497
Bom                            470
                             ...
Entregue Rapido                  1
Nota Máxima!                     1
Não Foi Entregue O Pedido        1
Otima Embalagem                  1
Foto Enganosa                    1
Name: count, Length: 3464, dtype: int64

In [13]:
#dc['review_comment_message']=dc['review_comment_message'].fillna('No Comment Message') 
def comment_message (x):
    if pd.isna(x):
        return 'No Comment Message'

    x = str(x).lower() 
    if 'muito' in x and 'bom' in x or 'otimo' in x: 
        return 'Muito bom' 
    elif 'bom' in x:
        return 'Bom'  
    elif 'super' in x and 'recomendo' in x :
        return 'Super recomendo'
    elif 'recomendo' in x:
        return 'Recomendo' 

    return x.title().strip() 

dc['review_comment_message']=dc['review_comment_message'].apply(comment_message) 
dc['review_comment_message'].value_counts(dropna=False)

review_comment_message
No Comment Message                                                                                                                                                                                       58247
Muito bom                                                                                                                                                                                                 3235
Recomendo                                                                                                                                                                                                 3070
Bom                                                                                                                                                                                                       1919
Super recomendo                                                                                                                                                                                            664
                                                                                                                                                                                                         ...
Tive Um Problema Na Entrega Em Que O Correio Colocou No Site Como Entregue Dia 19/02 Mais Nao Tinha Entregue Tentei Contato Com Lannister E A Loja Em Questao E Impossivel Por Fone Nem Resposta Tive        1
Para Este Produto Recebi De Acordo Com A Compra Realizada!                                                                                                                                                   1
Entregou Dentro Do Prazo. O Produto Chegou Em Condições Perfeitas. Estou Muito Satisfeita!                                                                                                                   1
O Produto Não Foi Enviado Com Nf, Não Existe Venda Sem Nf, Com Certeza Fico No Aguardo Do Envio Da Nf Podendo Ser Por E-Mail.                                                                                1
Meu Produto Chegou E Ja Tenho Que Devolver, Pois Está Com Defeito , Não Segurar Carga                                                                                                                        1
Name: count, Length: 28186, dtype: int64

In [14]:
dc.info()
dc.head()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     99224 non-null  str
 4   review_comment_message   99224 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,No Comment Title,No Comment Message,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,No Comment Title,No Comment Message,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,No Comment Title,No Comment Message,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,No Comment Title,Recebi Bem Antes Do Prazo Estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,No Comment Title,Parabéns Lojas Lannister Adorei Comprar Pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [15]:
dc['review_creation_date']=pd.to_datetime(dc['review_creation_date'], format='%Y-%m-%d %H:%M:%S')

In [16]:
dc['review_answer_timestamp']=pd.to_datetime(dc['review_answer_timestamp'], format='%Y-%m-%d %H:%M:%S')

In [21]:
dc.info()
dc.head()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     99224 non-null  str
 4   review_comment_message   99224 non-null  str
 5   review_creation_date     99224 non-null  datetime64[us]
 6   review_answer_timestamp  99224 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(1), str(4)
memory usage: 5.3 MB

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,No Comment Title,No Comment Message,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,No Comment Title,No Comment Message,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,No Comment Title,No Comment Message,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,No Comment Title,Recebi Bem Antes Do Prazo Estipulado.,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,No Comment Title,Parabéns Lojas Lannister Adorei Comprar Pela I...,2018-03-01,2018-03-02 10:26:53

In [18]:
dc.to_csv('clean_dataset/order_review_cleaned.csv', index=False, encoding='utf-8')