In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
dc = pd.read_csv('raw_dataset/olist_orders_dataset.csv') 
dc.info() 
dc.head()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [3]:
dc.columns.is_unique #Check data duplikat di setiap kolom (output: True)

True

In [9]:
#Check jumlah missing value di setiap kolom  
print('order_id: ', dc['order_id'].isna().sum())
print('customer_id: ', dc['customer_id'].isna().sum())
print('order_status: ', dc['order_status'].isna().sum())
print('order_purchase_timestamp: ', dc['order_purchase_timestamp'].isna().sum()) 
print('order_approved_at: ', dc['order_approved_at'].isna().sum()) 
print('order_delivered_carrier_date: ', dc['order_delivered_carrier_date'].isna().sum()) 
print('order_delivered_customer_date: ', dc['order_delivered_customer_date'].isna().sum()) 
print('order_estimated_delivery_date: ', dc['order_estimated_delivery_date'].isna().sum())

order_id:  0
customer_id:  0
order_status:  0
order_purchase_timestamp:  0
order_approved_at:  160
order_delivered_carrier_date:  1783
order_delivered_customer_date:  2965
order_estimated_delivery_date:  0

In [21]:
dc['order_approved_at'].value_counts(dropna = False) #Check kategori penulisan kolom order_approve_at

order_approved_at
NaT                    160
2018-02-27 04:31:10      9
2017-11-07 07:30:38      7
2018-02-06 05:31:52      7
2018-07-05 16:33:01      7
                      ...
2017-03-09 09:54:05      1
2018-02-06 13:10:37      1
2017-08-27 15:04:16      1
2018-01-08 21:36:21      1
2018-03-09 11:20:28      1
Name: count, Length: 90734, dtype: int64

In [17]:
dc['order_approved_at']=pd.to_datetime(dc['order_approved_at'], format='%Y-%m-%d %H:%M:%S')

In [19]:
dc['order_purchase_timestamp']=pd.to_datetime(dc['order_purchase_timestamp'], format='%Y-%m-%d %H:%M:%S')

In [22]:
dc['order_delivered_carrier_date']=pd.to_datetime(dc['order_delivered_carrier_date'], format='%Y-%m-%d %H:%M:%S')

In [23]:
dc['order_delivered_customer_date']=pd.to_datetime(dc['order_delivered_customer_date'], format='%Y-%m-%d %H:%M:%S')

In [24]:
dc['order_estimated_delivery_date']=pd.to_datetime(dc['order_estimated_delivery_date'], format='%Y-%m-%d %H:%M:%S')

In [25]:
dc.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](5), str(3)
memory usage: 6.1 MB

In [30]:
dc.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [29]:
dc['order_status'].value_counts(dropna=False)

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [31]:
dc.to_csv('clean_dataset/orders_cleaned.csv', index=False, encoding='utf-8')