In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dc = pd.read_csv('raw_dataset/product_category_name_translation.csv') 
dc.info() 
dc.head()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [3]:
dc.columns.is_unique #Check data duplikat di setiap kolom (output: True)

True

In [4]:
#Check jumlah missing value di setiap kolom  
print('product_category_name: ', dc['product_category_name'].isna().sum())
print('product_category_name_english: ', dc['product_category_name_english'].isna().sum())

product_category_name:  0
product_category_name_english:  0

In [5]:
dc['product_category_name'].value_counts(dropna=False)

product_category_name
beleza_saude                     1
informatica_acessorios           1
automotivo                       1
cama_mesa_banho                  1
moveis_decoracao                 1
                                ..
flores                           1
artes_e_artesanato               1
fraldas_higiene                  1
fashion_roupa_infanto_juvenil    1
seguros_e_servicos               1
Name: count, Length: 71, dtype: int64

In [6]:
dc['product_category_name']=dc['product_category_name'].str.replace('_', ' ') 
dc['product_category_name'].value_counts(dropna=False)

product_category_name
beleza saude                     1
informatica acessorios           1
automotivo                       1
cama mesa banho                  1
moveis decoracao                 1
                                ..
flores                           1
artes e artesanato               1
fraldas higiene                  1
fashion roupa infanto juvenil    1
seguros e servicos               1
Name: count, Length: 71, dtype: int64

In [7]:
dc['product_category_name_english']=dc['product_category_name_english'].str.replace('_', ' ') 
dc['product_category_name_english'].value_counts(dropna=False)

product_category_name_english
health beauty                1
computers accessories        1
auto                         1
bed bath table               1
furniture decor              1
                            ..
flowers                      1
arts and craftmanship        1
diapers and hygiene          1
fashion childrens clothes    1
security and services        1
Name: count, Length: 71, dtype: int64

In [9]:
dc.info()
dc.tail()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

            product_category_name product_category_name_english
66                         flores                       flowers
67             artes e artesanato         arts and craftmanship
68                fraldas higiene           diapers and hygiene
69  fashion roupa infanto juvenil     fashion childrens clothes
70             seguros e servicos         security and services

In [10]:
dc.to_csv('clean_dataset/product_category_cleaned.csv', index=False, encoding='utf-8')