In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dc = pd.read_csv('raw_dataset/olist_products_dataset.csv') 
dc.info() 
dc.head()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [3]:
dc.columns.is_unique #Check data duplikat di setiap kolom (output: True)

True

In [4]:
#Check jumlah missing value di setiap kolom  
print('product_id: ', dc['product_id'].isna().sum())
print('product_category_name: ', dc['product_category_name'].isna().sum())
print('product_name_lenght: ', dc['product_name_lenght'].isna().sum())
print('product_description_lenght: ', dc['product_description_lenght'].isna().sum())
print('product_photos_qty: ', dc['product_photos_qty'].isna().sum())
print('product_weight_g: ', dc['product_weight_g'].isna().sum())
print('product_length_cm: ', dc['product_length_cm'].isna().sum())
print('product_height_cm: ', dc['product_height_cm'].isna().sum())
print('product_width_cm: ', dc['product_width_cm'].isna().sum())

product_id:  0
product_category_name:  610
product_name_lenght:  610
product_description_lenght:  610
product_photos_qty:  610
product_weight_g:  2
product_length_cm:  2
product_height_cm:  2
product_width_cm:  2

In [6]:
dc['product_category_name']=dc['product_category_name'].fillna('Unknown Category Name') 
dc['product_category_name'].value_counts(dropna=False)

product_category_name
cama_mesa_banho                  3029
esporte_lazer                    2867
moveis_decoracao                 2657
beleza_saude                     2444
utilidades_domesticas            2335
                                 ...
fashion_roupa_infanto_juvenil       5
casa_conforto_2                     5
pc_gamer                            3
seguros_e_servicos                  2
cds_dvds_musicais                   1
Name: count, Length: 74, dtype: int64

In [7]:
dc['product_name_lenght']=dc['product_name_lenght'].fillna(0) 
dc['product_name_lenght'].value_counts(dropna=False)

product_name_lenght
60.0    2182
59.0    2025
58.0    1887
57.0    1719
55.0    1683
        ...
66.0       1
72.0       1
67.0       1
76.0       1
6.0        1
Name: count, Length: 67, dtype: int64

In [8]:
dc['product_description_lenght']=dc['product_description_lenght'].fillna(0) 
dc['product_description_lenght'].value_counts(dropna=False)

product_description_lenght
0.0       610
404.0      94
729.0      86
703.0      66
651.0      66
         ...
2752.0      1
2805.0      1
2836.0      1
3364.0      1
2207.0      1
Name: count, Length: 2961, dtype: int64

In [9]:
dc['product_photos_qty']=dc['product_photos_qty'].fillna(0) 
dc['product_photos_qty'].value_counts(dropna=False)

product_photos_qty
1.0     16489
2.0      6263
3.0      3860
4.0      2428
5.0      1484
6.0       968
0.0       610
7.0       343
8.0       192
9.0       105
10.0       95
11.0       46
12.0       35
13.0        9
15.0        8
17.0        7
14.0        5
18.0        2
20.0        1
19.0        1
Name: count, dtype: int64

In [10]:
dc['product_weight_g']=dc['product_weight_g'].fillna(dc['product_weight_g'].median())
dc['product_weight_g'].value_counts(dropna=False)

product_weight_g
200.0     2084
300.0     1561
150.0     1259
400.0     1206
100.0     1188
          ...
908.0        1
5408.0       1
1206.0       1
934.0        1
1920.0       1
Name: count, Length: 2204, dtype: int64

In [11]:
dc['product_length_cm']=dc['product_length_cm'].fillna(dc['product_length_cm'].median())
dc['product_length_cm'].value_counts(dropna=False)

product_length_cm
16.0    5520
20.0    2816
30.0    2029
18.0    1502
25.0    1389
        ...
96.0       4
10.0       3
8.0        2
9.0        2
7.0        1
Name: count, Length: 99, dtype: int64

In [12]:
dc['product_height_cm']=dc['product_height_cm'].fillna(dc['product_height_cm'].median())
dc['product_height_cm'].value_counts(dropna=False)

product_height_cm
10.0    2548
15.0    2022
20.0    1991
16.0    1595
11.0    1551
        ...
98.0       2
97.0       2
99.0       1
89.0       1
94.0       1
Name: count, Length: 102, dtype: int64

In [13]:
dc['product_width_cm']=dc['product_width_cm'].fillna(dc['product_width_cm'].median())
dc['product_width_cm'].value_counts(dropna=False)

product_width_cm
11.0     3718
20.0     3055
16.0     2808
15.0     2393
30.0     1786
         ...
103.0       1
118.0       1
97.0        1
77.0        1
104.0       1
Name: count, Length: 95, dtype: int64

In [15]:
dc.info()
dc.head()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32951 non-null  str
 2   product_name_lenght         32951 non-null  float64
 3   product_description_lenght  32951 non-null  float64
 4   product_photos_qty          32951 non-null  float64
 5   product_weight_g            32951 non-null  float64
 6   product_length_cm           32951 non-null  float64
 7   product_height_cm           32951 non-null  float64
 8   product_width_cm            32951 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [17]:
dc['product_name_lenght']=dc['product_name_lenght'].astype(int)
dc['product_description_lenght']=dc['product_description_lenght'].astype(int)
dc['product_photos_qty']=dc['product_photos_qty'].astype(int)
dc.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32951 non-null  str
 2   product_name_lenght         32951 non-null  int64
 3   product_description_lenght  32951 non-null  int64
 4   product_photos_qty          32951 non-null  int64
 5   product_weight_g            32951 non-null  float64
 6   product_length_cm           32951 non-null  float64
 7   product_height_cm           32951 non-null  float64
 8   product_width_cm            32951 non-null  float64
dtypes: float64(4), int64(3), str(2)
memory usage: 2.3 MB

In [19]:
dc['product_category_name']=dc['product_category_name'].str.replace('_',' ') 
dc['product_category_name'].value_counts(dropna=False)

product_category_name
cama mesa banho                  3029
esporte lazer                    2867
moveis decoracao                 2657
beleza saude                     2444
utilidades domesticas            2335
                                 ...
fashion roupa infanto juvenil       5
casa conforto 2                     5
pc gamer                            3
seguros e servicos                  2
cds dvds musicais                   1
Name: count, Length: 74, dtype: int64

In [22]:
dc.tail()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis decoracao,45,67,2,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao ferramentas iluminacao,41,971,1,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama mesa banho,50,799,1,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica acessorios,60,156,2,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama mesa banho,58,309,1,2083.0,12.0,2.0,7.0

In [23]:
dc.to_csv('clean_dataset/products_cleaned.csv', index=False, encoding='utf-8')